### ISSUE TITLE
Slow Image Load Time 

### ISSUE THREAD

**Issue by tcbutler320** [tcbutler320/Jekyll-Theme-Dumbarton#18]
## Slow Image Load Time 
Upon opening /blog.html, images take a considerable time to load. Consider possibilities to optimize images and consider caching/preview image functions/plugins. 

*Potential Options*
[jekyll-speed](https://blog.webjeda.com/jekyll-speed/#2-optimize-images)

**Comment by MichaelCurrin** [comment]
I have a plugin I use here for resizing

https://github.com/MichaelCurrin/jekyll-resize

**Comment by MichaelCurrin** [comment]
I list some alternatives in the README too.

**Comment by tcbutler320** [comment]
Fixed inadvertently in #50, images are no longer previewed on blog page with new UI layout
