### ISSUE TITLE
Problem builds with bibliography tag

### ISSUE THREAD

**Issue by LeonardoFurtado** [tcbutler320/Jekyll-Theme-Dumbarton#44]
GithubPages settings show 
`
Your site is having problems building: The tag bibliography on line 80 in /_layouts/home.html is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error. 
`

**Comment by tcbutler320** [comment]
Hey sorry about it but Github Pages does not support Jekyll-Scholar yet. I tried to mention this on the readme under the [compatability](https://github.com/tcbutler320/Jekyll-Theme-Dumbarton#about) section. You can read more about this on the official [Jekyll-Scholar readme](https://github.com/inukshuk/jekyll-scholar#github-pages) , but an except is below

> Note that it is not possible to use this plugin with the default Github pages workflow. Github does not allow any but a few select plugins to run for security reasons, and Jekyll-Scholar is not among them. You will have to generate your site locally and push the results to the master resp. gh-pages branch of your site repository. You can keep sources, configuration and plugins in a separate branch; see e.g. here for details.

If you want another free hosting provider you can use [Netlify](https://www.netlify.com/). That is where I host my site and it integrates seamlessly with github.
